### ISSUE TITLE
fresh install fails

### ISSUE THREAD

**Issue by huntsmanscope** [AstroHuntsman/huntsman-pocs#30]
@moniquecockram and @lspitler tried setting up a fresh install of Huntsman/POCS on the mac mini we were using at SSO. On step 1 here:
https://github.com/AstroHuntsman/huntsman-pocs/wiki/Startup-Huntsman-POCS 

We got the following error:

```
(16:18:19)-(lspitler)-(501)-> python $POCS/scripts/start_messenger.py
WARNING: OldEarthOrientationDataWarning: Your version of the IERS Bulletin A is 25.2 days old. For best precision (on the order of arcseconds), you must download an up-to-date IERS Bulletin A table. To do so, run:

>>> from astroplan import download_IERS_A
>>> download_IERS_A()
 [astroplan.utils]
Traceback (most recent call last):
  File "/var/huntsman/POCS/scripts/start_messenger.py", line 3, in <module>
    from pocs.utils.messaging import PanMessaging
  File "/private/var/huntsman/POCS/pocs/__init__.py", line 11, in <module>
    from pocs.core import POCS
  File "/private/var/huntsman/POCS/pocs/core.py", line 16, in <module>
    from pocs.utils.messaging import PanMessaging
  File "/private/var/huntsman/POCS/pocs/utils/messaging.py", line 16, in <module>
    class PanMessaging(object):
  File "/private/var/huntsman/POCS/pocs/utils/messaging.py", line 22, in PanMessaging
    logger = get_root_logger()
  File "/private/var/huntsman/POCS/pocs/utils/logger.py", line 94, in get_root_logger
    os.symlink(full_log_fname, log_symlink)
FileNotFoundError: [Errno 2] No such file or directory: '/var/huntsman/logs/start_messenger.py-708-20180108T051903Z-all.log' -> '/var/huntsman/logs/start_messenger.py.log'
```

**Comment by huntsmanscope** [comment]
Hold on!! We did not follow all instructions on this page:

https://github.com/AstroHuntsman/huntsman-pocs/wiki/Installing-Huntsman-Machine 

It works fine!
